force-app/main/default/objects/D2C_VTO_POS_Session__c/D2C_VTO_POS_Session__c.object-meta.xml
<CustomObject>
    <label>POS Session</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POS Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/D2C_VTO_POS_Session__c/fields/D2C_VTO_Status__c.field-meta.xml
<CustomField>
    <fullName>D2C_VTO_Status__c</fullName>
    <description>This field helps to identify whether the POS Session is open, in progress or closed.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/D2C_VTO_POS_Session_Activity__c/D2C_VTO_POS_Session_Activity__c.object-meta.xml
<CustomObject>
    <label>POS Session Activity</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POS Session Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/D2C_VTO_POS_Session_Activity__c/fields/D2C_VTO_Command__c.field-meta.xml
<CustomField>
    <fullName>D2C_VTO_Command__c</fullName>
    <description
    >This field holds the rules/commands to identify the remote actions done so that appropriate action can be taken up at the POS screen.</description>
    <label>Command</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QR Code scanned</fullName>
            </value>
            <value>
                <fullName>Open VTO session</fullName>
            </value>
            <value>
                <fullName>Close VTO session</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/D2C_VTO_POS_Session_Activity__c/fields/D2C_VTO_POS_Session__c.field-meta.xml
<CustomField>
    <fullName>D2C_VTO_POS_Session__c</fullName>
    <description>This lookup field is linkage between POS Session and POS Session Activity record</description>
    <label>POS Session</label>
    <referenceTo>D2C_VTO_POS_Session__c</referenceTo>
    <relationshipLabel>POS Session Activities</relationshipLabel>
    <relationshipName>D2C_VTO_POS_Session_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/D2C_VTO_POS_Session_Activity__c/fields/D2C_VTO_Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>D2C_VTO_Product_SKU__c</fullName>
    <description>This field contains the product SKU of the product against which the VTO needs to be opened</description>
    <label>Product SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/D2C_VTO_SessionControllerTest.cls
/*************************************************************************************************************
 * This class tests D2C_VTO_SessionController
 *
 * @author – Shrikant Dangi
 ***************************************************************************************************************/
@isTest
private class D2C_VTO_SessionControllerTest {
    /**
     * @description Tests that a sessionId is returned when createSessionRecord is called
     */
    @IsTest
    static void positiveSessionCreationTest() {
        Test.startTest();
        Id sessionId = D2C_VTO_SessionController.createSessionRecord(D2C_VTO_Constants.SESSION_STATUS_OPEN, Datetime.now());
        Test.stopTest();
        Assert.areNotEqual(null, sessionId, 'createSessionRecord must return non null id');
    }

    /**
     * @description Tests checkIfActivityRecordExists returns true when
     * activity with SA_COMMAND_QR_CODE_SCANNED is present
     */
    @isTest
    static void positiveNegativeQrScanTest() {
        Test.startTest();
        Id sessionId = D2C_VTO_SessionController.createSessionRecord(D2C_VTO_Constants.SESSION_STATUS_OPEN, Datetime.now());
        Assert.isFalse(D2C_VTO_SessionController.checkIfActivityRecordExists(sessionId, D2C_VTO_Constants.SA_COMMAND_QR_CODE_SCANNED), 'should return false');
        D2C_VTO_SessionController.createSessionActivityIfNotExists(sessionId, D2C_VTO_Constants.SA_COMMAND_QR_CODE_SCANNED);
        D2C_VTO_SessionController.createSessionActivityIfNotExists(sessionId, D2C_VTO_Constants.SA_COMMAND_QR_CODE_SCANNED);
        D2C_VTO_SessionController.updateSessionStatus(sessionId, D2C_VTO_Constants.SESSION_STATUS_IN_PROGRESS);
        Test.stopTest();
        Assert.isTrue(D2C_VTO_SessionController.checkIfActivityRecordExists(sessionId, D2C_VTO_Constants.SA_COMMAND_QR_CODE_SCANNED), 'should return true');
        List<D2C_VTO_POS_Session_Activity__c> posSessionActivityLst = [
            SELECT Id, D2C_VTO_Product_SKU__c
            FROM D2C_VTO_POS_Session_Activity__c
            WHERE D2C_VTO_POS_Session__c = :sessionId AND D2C_VTO_Command__c = :D2C_VTO_Constants.SA_COMMAND_QR_CODE_SCANNED
        ];
        Assert.areEqual(1, posSessionActivityLst.size(), 'should create only one qrCodeScanned activity');
    }

    /**
     * @description Tests updateSessionStatus to mark session in progress
     */
    @IsTest
    static void markSessionInProgressTest() {
        Id sessionId = D2C_VTO_SessionController.createSessionRecord(D2C_VTO_Constants.SESSION_STATUS_OPEN, Datetime.now());
        Test.startTest();
        D2C_VTO_SessionController.updateSessionStatus(sessionId, D2C_VTO_Constants.SESSION_STATUS_IN_PROGRESS);
        Test.stopTest();

        List<D2C_VTO_POS_Session__c> inProgressSession = [
            SELECT Id
            FROM D2C_VTO_POS_Session__c
            WHERE Id = :sessionId AND D2C_VTO_Status__c = :D2C_VTO_Constants.SESSION_STATUS_IN_PROGRESS
        ];
        Assert.isFalse(inProgressSession.isEmpty(), 'must mark session in progress');
    }
}