force-app/main/default/objects/D2C_VTO_POS_Session__c/D2C_VTO_POS_Session__c.object-meta.xml
<CustomObject>
    <label>POS Session</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POS Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/D2C_VTO_POS_Session__c/fields/D2C_VTO_Status__c.field-meta.xml
<CustomField>
    <fullName>D2C_VTO_Status__c</fullName>
    <description>This field helps to identify whether the POS Session is open, in progress or closed.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/D2C_VTO_POS_Session_Activity__c/D2C_VTO_POS_Session_Activity__c.object-meta.xml
<CustomObject>
    <label>POS Session Activity</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POS Session Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/D2C_VTO_POS_Session_Activity__c/fields/D2C_VTO_Command__c.field-meta.xml
<CustomField>
    <fullName>D2C_VTO_Command__c</fullName>
    <description
    >This field holds the rules/commands to identify the remote actions done so that appropriate action can be taken up at the POS screen.</description>
    <label>Command</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QR Code scanned</fullName>
            </value>
            <value>
                <fullName>Open VTO session</fullName>
            </value>
            <value>
                <fullName>Close VTO session</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/D2C_VTO_POS_Session_Activity__c/fields/D2C_VTO_POS_Session__c.field-meta.xml
<CustomField>
    <fullName>D2C_VTO_POS_Session__c</fullName>
    <description>This lookup field is linkage between POS Session and POS Session Activity record</description>
    <label>POS Session</label>
    <referenceTo>D2C_VTO_POS_Session__c</referenceTo>
    <relationshipLabel>POS Session Activities</relationshipLabel>
    <relationshipName>D2C_VTO_POS_Session_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/D2C_VTO_Constants.cls
/*************************************************************************************************************
 * This class will have all the constants needed at various places for D2C
 *
 * @author – Shrikant Dangi
 ***************************************************************************************************************/
public with sharing class D2C_VTO_Constants {
    // These constants have values from field: D2C_VTO_POS_Session__c.D2C_VTO_Status__c
    public static final String SESSION_STATUS_OPEN = 'Open';
    public static final String SESSION_STATUS_IN_PROGRESS = 'In Progress';
    public static final String SESSION_STATUS_CLOSED = 'Closed';

    // These constants have values from field: D2C_VTO_POS_Session_Activity__c.D2C_VTO_Command__c
    public static final String SA_COMMAND_QR_CODE_SCANNED = 'QR Code scanned';
    public static final String SA_COMMAND_OPEN_VTO_SESSION = 'Open VTO session';
    public static final String SA_COMMAND_CLOSE_VTO_SESSION = 'Close VTO session';

    /* Start : DVM21-45 */
    public static final String PRODUCT_IMAGE = 'Product Image';
    public static final String VTO_VALUE = 'VTO';
    /* End : DVM21-45 */
}