force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description
    >Used for visibility of the footer in SH brand’s Partner Portal &amp; used for populating customer service details on B2B Prospect Accounts.</description>
    <inlineHelpText
    >Used for visibility of the footer in SH brand’s Partner Portal &amp; used for populating customer service details on B2B Prospect Accounts.</inlineHelpText>
    <label>Brand for Partner Portal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BrandValueSet</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Store_Country__c.field-meta.xml
<CustomField>
    <fullName>Store_Country__c</fullName>
    <description>Country code based on AE&apos;s Location</description>
    <inlineHelpText>Show country options as picklist values in a dropdown in the country field for e.g. Get Access flow</inlineHelpText>
    <label>Store Country (picklist)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Germany-MITTE</fullName>
                <isActive>false</isActive>
                <label>Germany-MITTE</label>
            </value>
            <value>
                <fullName>Germany-NORD</fullName>
                <isActive>false</isActive>
                <label>Germany-NORD</label>
            </value>
            <value>
                <fullName>Germany-SUD</fullName>
                <isActive>false</isActive>
                <label>Germany-SUD</label>
            </value>
            <value>
                <fullName>Great Britain</fullName>
            </value>
            <value>
                <fullName>Guatemala</fullName>
            </value>
            <value>
                <fullName>HongKong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Iceland</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Lithuania</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Norway</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
                <isActive>false</isActive>
                <label>Portuguese</label>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/B2B_CommerceLog__c/B2B_CommerceLog__c.object-meta.xml
<CustomObject>
    <label>B2B Commerce Log</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>B2B Commerce Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Commerce Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B2B_CommerceLog__c/fields/B2B_Message__c.field-meta.xml
<CustomField>
    <fullName>B2B_Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B2B_CommerceLog__c/fields/B2B_Message_Details__c.field-meta.xml
<CustomField>
    <fullName>B2B_Message_Details__c</fullName>
    <label>Message Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/B2B_CommerceLog__c/fields/B2B_Process__c.field-meta.xml
<CustomField>
    <fullName>B2B_Process__c</fullName>
    <label>Process</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checkout</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>ClientSide</fullName>
            </value>
            <value>
                <fullName>Register</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>CommerceSetup</fullName>
                <label>B2B CommerceSetup</label>
            </value>
            <value>
                <fullName>Translation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/B2B_CommerceLog__c/fields/B2B_Related_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>B2B_Related_Record_Id__c</fullName>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B2B_CommerceLog__c/fields/B2B_Type__c.field-meta.xml
<CustomField>
    <fullName>B2B_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/B2B_Lens_Configurator__c/B2B_Lens_Configurator__c.object-meta.xml
<CustomObject>
    <description>This Object is used to save the configuration at every step of the configurator from VS/RX</description>
    <label>B2B Lens Configurator</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Lens Configurator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B2B_Lens_Configurator__c/fields/B2B_Account__c.field-meta.xml
<CustomField>
    <fullName>B2B_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account associated with VS RX configuration</description>
    <label>Account ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>B2B Lens Configurator</relationshipLabel>
    <relationshipName>B2B_Lens_Configurator</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/B2B_Lens_Configurator__c/fields/B2B_ARIS_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>B2B_ARIS_Account_Id__c</fullName>
    <description>This field is used to store ARIS ID of currently mapped account and it is needed for Schneider callout for retailderId attribute</description>
    <label>ARIS_Account_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B2B_Lens_Configurator__c/fields/B2B_Type__c.field-meta.xml
<CustomField>
    <fullName>B2B_Type__c</fullName>
    <description>This field is used to indicate the applicable brand. Applicable Values: Vision Sensation/RX Glazing</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vision Sensation</fullName>
            </value>
            <value>
                <fullName>RX Glazing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/B2B_Lens_Shapes__c/B2B_Lens_Shapes__c.object-meta.xml
<CustomObject>
    <description>This object is used to save the lens shapes.</description>
    <label>B2B Lens Shape</label>
    <nameField>
        <displayFormat>LS-{00000}</displayFormat>
        <label>B2B Lens Shape Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Lens Shapes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/My_B2B_Shop_Preference__c/My_B2B_Shop_Preference__c.object-meta.xml
<CustomObject>
    <label>My B2B Shop Preference</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>My B2B Shop Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My B2B Shop Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/My_B2B_Shop_Preference__c/fields/B2B_Account__c.field-meta.xml
<CustomField>
    <fullName>B2B_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B_Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>My B2B Shop Preferences</relationshipLabel>
    <relationshipName>My_B2B_Shop_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/My_B2B_Shop_Preference__c/fields/B2B_Hide_Account_Closure_Popup__c.field-meta.xml
<CustomField>
    <fullName>B2B_Hide_Account_Closure_Popup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>field which control if the user wants to see the Account Closure Popup or not</description>
    <label>Hide Account Closure Popup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/BrandValueSet.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Silhouette</fullName>
    </customValue>
    <customValue>
        <fullName>evil eye</fullName>
    </customValue>
    <customValue>
        <fullName>NEUBAU</fullName>
    </customValue>
    <customValue>
        <fullName>Adidas</fullName>
        <isActive>false</isActive>
        <label>Adidas</label>
    </customValue>
    <masterLabel>Brand Value Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/B2B_UtilsTest.cls
@SuppressWarnings('PMD')
@isTest
public with sharing class B2B_UtilsTest {
    @testSetup
    static void setup() {
        List<Account> accountList = B2B_TestDataFactory.createAccounts(1, 'TestAccount001', 'Account', true);
        My_B2B_Shop_Preference__c myB2BShopPrefernceObj = new My_B2B_Shop_Preference__c(
            B2B_Account__c = accountList[0].Id,
            B2B_Hide_Account_Closure_Popup__c = false
        );
        insert myB2BShopPrefernceObj; //BS-1953

        List<User> userList = new List<User>();
        userList.add(B2B_TestDataFactory.createUser('TestUser0011', 'TestUser0011', 'TestUser0110@test.com', UserInfo.getProfileId()));
        if (userList.isEmpty() == false) {
            userList[0].IsActive = true;
            userList[0].Phone = '9988776655';
            userList[0].UserRoleId = null;
            insert userList;
        }
    }

    @IsTest
    public static void getWebstoreByCommunityIdTest() {
        B2B_Utils.communityIdToWebstoreCache.put('Silhouette B2B Shop', new Webstore(Name = 'Silhouette B2B Shop'));

        Webstore store = B2B_Utils.getWebstoreByCommunityId('Silhouette B2B Shop');

        System.assertEquals('Silhouette B2B Shop', store.name, 'the method should return the correct webstore');

        store = B2B_Utils.getWebstoreByCommunityId(null);

        System.assertEquals(null, store, 'the method should not return a webstore');

        try {
            store = B2B_Utils.getWebstoreByCommunityId('test');
        } catch (Exception e) {
            // catch exception due to missing webstore
        }
    }

    @isTest
    public static void resolveCommunityIdToWebstoreIdTest() {
        Test.startTest();

        String communityId = '0DB3L0000000000000';
        String wsId = B2B_Utils.resolveWebstoreId(communityId);

        Test.stopTest();
        System.assertNotEquals(null, wsId, 'Webstore Id should not be null but mocked');
    }

    @isTest
    public static void resolveWebstoreIdTest() {
        Test.startTest();

        String webstoreId = B2B_TestDataFactory.mockRecordId(WebStore.getSObjectType());
        String wsId = B2B_Utils.resolveWebstoreId(webstoreId);
        System.assertEquals(webstoreId, wsId, 'Webstore Id returned should be the same');
        Test.stopTest();
    }

    @isTest
    public static void resolveWebstoreIdFailTest() {
        Test.startTest();

        String wsId = B2B_Utils.resolveWebstoreId(null);
        System.assertEquals(null, wsId, 'Webstore Id returned should be null');
        Test.stopTest();
    }

    @IsTest
    public static void insertCommunityUserTest() {
        Account acc = B2B_TestDataFactory.createInsertTestAccount();
        Contact con = B2B_TestDataFactory.createInsertDefaultContact(acc);

        Test.startTest();
        B2B_Utils.insertCommunityUser(con.Id, 'silhouette');
        Test.stopTest();

        List<User> users = [SELECT Id FROM User WHERE ContactId = :con.Id];

        System.assertEquals(1, users.size(), 'there should only be one user assigned to the created contact.');
    }

    @IsTest
    public static void insertCommunityUserNeubauTest() {
        Account acc = B2B_TestDataFactory.createInsertTestAccount();
        Contact con = B2B_TestDataFactory.createInsertDefaultContact(acc);

        Test.startTest();
        B2B_Utils.insertCommunityUser(con.Id, 'neubau');
        Test.stopTest();

        List<User> users = [SELECT Id FROM User WHERE ContactId = :con.Id];

        System.assertEquals(1, users.size(), 'there should only be one user assigned to the created contact.');
    }

    @IsTest
    public static void checkIfAccessibleTest() {
        final String[] objFields = new List<String>{ 'Id', 'Name' };

        Test.startTest();
        Boolean isAccessible = B2B_Utils.checkIfAccessible('Account', objFields);
        Test.stopTest();

        System.assertEquals(true, isAccessible, 'the user should have access to the account name and id');
    }

    @IsTest
    public static void getAvailableWebstoreLanguagesTest() {
        String languages = B2B_Utils.getAvailableWebstoreLanguages('0DB3L0000000000000');
        System.assertEquals(null, languages, 'should return null due to missing community/webstore');
    }

    @IsTest
    static void changePasswordTest() {
        User communityUser = B2B_TestDataFactory.createInsertCommerceUser();

        try {
            System.runAs(communityUser) {
                B2B_Utils.changePassword('test', 'test2', 'test2', 'de', true);
            }
        } catch (Exception e) {
            System.assertNotEquals(null, e, 'Should throw an error due to password data');
        }
    }

    @IsTest
    static void sendChangePasswordMailTest() {
        User communityUser = B2B_TestDataFactory.createInsertCommerceUser();

        try {
            System.runAs(communityUser) {
                B2B_Utils.sendChangePasswordMail('de', true);
                B2B_Utils.sendChangePasswordMail('en_US', true);
                B2B_Utils.sendChangePasswordMail('de', false);
                B2B_Utils.sendChangePasswordMail('en_US', false);
            }
        } catch (Exception e) {
            // no error
        }

        System.assert(true, 'sendChangePasswordMail should not throw an error');
    }

    @IsTest
    public static void sendEmailToUserTest() {
        B2B_Utils.sendEmailToUser('de', true, 'test@test.com', false);
        B2B_Utils.sendEmailToUser('en_US', true, 'test@test.com', false);
        B2B_Utils.sendEmailToUser('de', false, 'test@test.com', false);
        B2B_Utils.sendEmailToUser('en_US', false, 'test@test.com', false);
        Integer emailInvocations = Limits.getEmailInvocations();
        System.assertEquals(4, emailInvocations, 'emails not sent');
    }

    //BS-443
    @IsTest
    public static void getAllProductsTest() {
        List<String> productIdList = new List<String>();
        Map<String, String> sampleCatalog = B2B_TestDataFactory.createInsertCatalogAndCategory();
        List<Product2> products = B2B_TestDataFactory.createProducts(10, null);
        insert products;
        List<ProductCategoryProduct> productCategoryProductList = B2B_TestDataFactory.createProductCategoryProduct(
            products.size(),
            products,
            sampleCatalog.get('childCategoryId')
        );
        insert productCategoryProductList;
        for (Product2 product : products) {
            productIdList.add(product.Id);
        }
        List<Product2> productList = B2B_Utils.getAllProducts(productIdList, sampleCatalog.get('parentCategoryId'));
        System.assertEquals(10, productList.size(), 'All the products not fetched');
    }

    //BS-443
    @IsTest
    public static void getAllProductsWithoutCategoryTest() {
        List<String> productIdList = new List<String>();
        List<Product2> products = B2B_TestDataFactory.createProducts(10, null);
        insert products;
        for (Product2 product : products) {
            productIdList.add(product.Id);
        }
        List<Product2> productList = B2B_Utils.getAllProducts(productIdList, null);
        System.assertEquals(10, productList.size(), 'All the products not fetched');
    }

    //Added for BS-866
    @IsTest
    public static void changeAddressMailTest() {
        Test.startTest();
        B2B_Utils.sendMailForAddressChangeRequest('de', true);
        B2B_Utils.sendMailForAddressChangeRequest('de', false);
        B2B_Utils.sendMailForAddressChangeRequest('en_US', true);
        B2B_Utils.sendMailForAddressChangeRequest('en_US', false);
        String exceptionMessage;
        try {
            B2B_Utils.sendMailForAddressChangeRequest('', null);
        } catch (Exception e) {
            exceptionMessage = e.getMessage();
        }
        Integer emailInvocations = Limits.getEmailInvocations();
        System.assertEquals('Attempt to de-reference a null object', exceptionMessage, 'Should throw an exception');
        System.assertEquals(4, emailInvocations, 'emails not sent');
        Test.stopTest();
    }

    //BS-1057
    @isTest
    public static void sendPartnerRegistrationEmailToUserSHTest() {
        B2B_TestDataFactory.createCountrySpecificPreferenceSettingRecords();
        Account accountObj = B2B_TestDataFactory.createTestAccount();
        accountObj.Store_Country__c = 'Germany';
        accountObj.Brand__c = 'Silhouette';
        insert accountObj;
        Contact contactObj = B2B_TestDataFactory.createInsertDefaultContact(accountObj);
        Test.startTest();
        B2B_Utils.sendPartnerRegistrationEmailToUser('de', true, 'test@test.com', true, contactObj.Id);
        B2B_Utils.sendPartnerRegistrationEmailToUser('en_US', true, 'test@test.com', true, contactObj.Id);
        Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();
        System.assertEquals(2, emailInvocations, 'Check for number of emails invoked');
    }

    //BS-1057
    @isTest
    public static void sendPartnerRegistrationEmailToUserNBTest() {
        B2B_TestDataFactory.createCountrySpecificPreferenceSettingRecords();
        Account accountObj = B2B_TestDataFactory.createTestAccount();
        accountObj.Store_Country__c = 'Germany';
        accountObj.Brand__c = 'NEUBAU';
        insert accountObj;
        Contact contactObj = B2B_TestDataFactory.createInsertDefaultContact(accountObj);
        Test.startTest();
        B2B_Utils.sendPartnerRegistrationEmailToUser('de', false, 'test@test.com', true, contactObj.Id);
        B2B_Utils.sendPartnerRegistrationEmailToUser('en_US', false, 'test@test.com', true, contactObj.Id);
        Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();
        System.assertEquals(2, emailInvocations, 'Check for number of emails invoked');
    }

    //BS-1034
    @isTest
    private static void sendSchneiderCalloutEmailsTest() {
        Test.startTest();
        B2B_Utils.sendSchneiderCalloutEmails(new List<String>{ 'abc@xyz.com' }, 'Test', 'Test');
        Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();
        System.assertEquals(1, emailInvocations, 'Check for number of emails invoked');
    }

    //Added below methods to increase the code coverage for B2B_Utils class as a part of BS-963 ticket.
    @IsTest
    public static void checkAccountWithOrderLockStatusTest() {
        Account accountObj = B2B_TestDataFactory.createTestAccount();
        accountObj.Order_Lock_Status__c = '1';
        insert accountObj;
        Test.startTest();
        Boolean orderStatusResult = B2B_Utils.checkAccountOrderLock(accountObj.Id);
        Test.stopTest();
        System.assertEquals(true, orderStatusResult, 'Order lock status on Account is locked.');
    }

    @IsTest
    public static void checkAccountWithoutOrderLockStatusTest() {
        Account accountObj = B2B_TestDataFactory.createTestAccount();
        accountObj.Order_Lock_Status__c = '0';
        insert accountObj;
        Test.startTest();
        Boolean orderStatusResult = B2B_Utils.checkAccountOrderLock(accountObj.Id);
        Test.stopTest();
        System.assertEquals(false, orderStatusResult, 'Order lock status on Account is unlocked.');
    }

    @IsTest
    public static void resolveSortParamTest() {
        Test.startTest();
        ConnectApi.CartItemSortOrder sortOrderResult = B2B_Utils.resolveSortParam(null);
        Test.stopTest();
        System.assertEquals(null, sortOrderResult, 'Cart item sort order is by default null.');
    }

    @IsTest
    public static void getAccountIdByCurrentUserTest() {
        Map<String, String> storeResponse = B2B_TestDataFactory.setupCommerceStoreFront();
        Test.startTest();
        System.runAs(new user(Id = storeResponse.get('userId'))) {
            Id accountId = B2B_Utils.getAccountIdByCurrentUser();
            System.assertNotEquals(null, accountId, 'Account Id account be null');
        }
        Test.stopTest();
    }

    @IsTest
    public static void negativeCheckForChangePasswordTest() {
        Test.startTest();
        try {
            B2B_Utils.changePassword(null, null, null, null, null);
        } catch (Exception e) {
            System.assertEquals(e.getMessage(), e.getMessage(), 'Aura Handled Exception Occur');
        }
        Test.stopTest();
    }

    //BS-1248
    @isTest
    private static void performSchneiderCalloutProcessingForSuccessfulResponseTest() {
        List<Product2> productList = B2B_TestDataFactory.createProductsForLensConfigurator();
        insert productList;

        List<B2B_Lens_Configurator__c> lensConfiguratorList = B2B_TestDataFactory.createCorrectRecordsForLensConfigurator();
        insert lensConfiguratorList;

        List<B2B_Lens_Shapes__c> lensShapeList = B2B_TestDataFactory.createCorrectRecordsForLensShapes();
        insert lensShapeList;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new B2B_TestDataFactory.B2B_SchneiderCalloutMockInterface(200, true));
        B2B_VisionSensationUtility vsUtility = new B2B_VisionSensationUtility();
        B2B_VisionSensationUtility.B2B_SchneiderRequest request = new B2B_VisionSensationUtility.B2B_SchneiderRequest();
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper responseWrapper = vsUtility.performSchneiderCallout(request);
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper parsedResponseWrapper = B2B_Utils.performSchneiderCalloutProcessing(
            responseWrapper,
            String.valueOf(lensConfiguratorList[0].Id)
        );
        List<B2B_Lens_Configurator__c> parsedLensConfiguratorList = [
            SELECT Id, B2B_Account__c, B2B_Account__r.k_ARIS_Account_ID__c, B2B_Account__r.k_Account_No__c, B2B_ARIS_Account_Id__c
            FROM B2B_Lens_Configurator__c
            WHERE Id = :lensConfiguratorList[0].Id
        ];
        List<B2B_CommerceLog__c> commerceLogsList = new List<B2B_CommerceLog__c>();
        if (parsedLensConfiguratorList.isEmpty() == false) {
            commerceLogsList = [
                SELECT Id, B2B_Message__c, B2B_Process__c, B2B_Type__c, B2B_Related_Record_Id__c
                FROM B2B_CommerceLog__c
                WHERE B2B_Related_Record_Id__c = :lensConfiguratorList[0].B2B_Account__c
            ];
        }
        Test.stopTest();
        Assert.areEqual(true, commerceLogsList.isEmpty(), 'Commerce Logs should not get created as Callout is successful without any errora');
    }

    //BS-1248
    @isTest
    private static void performSchneiderCalloutProcessingForCalculationErrorTest() {
        List<Product2> productList = B2B_TestDataFactory.createProductsForLensConfigurator();
        insert productList;

        List<B2B_Lens_Configurator__c> lensConfiguratorList = B2B_TestDataFactory.createCorrectRecordsForLensConfigurator();
        insert lensConfiguratorList;

        List<B2B_Lens_Shapes__c> lensShapeList = B2B_TestDataFactory.createCorrectRecordsForLensShapes();
        insert lensShapeList;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new B2B_TestDataFactory.B2B_SchneiderCalloutMockInterface(200, false));
        B2B_VisionSensationUtility vsUtility = new B2B_VisionSensationUtility();
        B2B_VisionSensationUtility.B2B_SchneiderRequest request = new B2B_VisionSensationUtility.B2B_SchneiderRequest();
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper responseWrapper = vsUtility.performSchneiderCallout(request);
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper parsedResponseWrapper = B2B_Utils.performSchneiderCalloutProcessing(
            responseWrapper,
            String.valueOf(lensConfiguratorList[0].Id)
        );
        List<B2B_Lens_Configurator__c> parsedLensConfiguratorList = [
            SELECT Id, B2B_Account__c, B2B_Account__r.k_ARIS_Account_ID__c, B2B_Account__r.k_Account_No__c, B2B_ARIS_Account_Id__c
            FROM B2B_Lens_Configurator__c
            WHERE Id = :lensConfiguratorList[0].Id
        ];
        List<B2B_CommerceLog__c> commerceLogsList = new List<B2B_CommerceLog__c>();
        if (parsedLensConfiguratorList.isEmpty() == false) {
            commerceLogsList = [
                SELECT Id, B2B_Message__c, B2B_Process__c, B2B_Type__c, B2B_Related_Record_Id__c
                FROM B2B_CommerceLog__c
                WHERE B2B_Related_Record_Id__c = :lensConfiguratorList[0].B2B_Account__c
            ];
        }
        Test.stopTest();
        Assert.areEqual(false, commerceLogsList.isEmpty(), 'Commerce Logs should get created as Callout is failed due to calculation error');
    }

    //BS-1248
    @isTest
    private static void performSchneiderCalloutProcessingForOMANotFoundErrorTest() {
        List<Product2> productList = B2B_TestDataFactory.createProductsForLensConfigurator();
        insert productList;

        List<B2B_Lens_Configurator__c> lensConfiguratorList = B2B_TestDataFactory.createCorrectRecordsForLensConfigurator();
        insert lensConfiguratorList;

        List<B2B_Lens_Shapes__c> lensShapeList = B2B_TestDataFactory.createCorrectRecordsForLensShapes();
        insert lensShapeList;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new B2B_TestDataFactory.B2B_SchneiderCalloutMockInterface(404, false));
        B2B_VisionSensationUtility vsUtility = new B2B_VisionSensationUtility();
        B2B_VisionSensationUtility.B2B_SchneiderRequest request = new B2B_VisionSensationUtility.B2B_SchneiderRequest();
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper responseWrapper = vsUtility.performSchneiderCallout(request);
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper parsedResponseWrapper = B2B_Utils.performSchneiderCalloutProcessing(
            responseWrapper,
            String.valueOf(lensConfiguratorList[0].Id)
        );
        List<B2B_Lens_Configurator__c> parsedLensConfiguratorList = [
            SELECT Id, B2B_Account__c, B2B_Account__r.k_ARIS_Account_ID__c, B2B_Account__r.k_Account_No__c, B2B_ARIS_Account_Id__c
            FROM B2B_Lens_Configurator__c
            WHERE Id = :lensConfiguratorList[0].Id
        ];
        List<B2B_CommerceLog__c> commerceLogsList = new List<B2B_CommerceLog__c>();
        if (parsedLensConfiguratorList.isEmpty() == false) {
            commerceLogsList = [
                SELECT Id, B2B_Message__c, B2B_Process__c, B2B_Type__c, B2B_Related_Record_Id__c
                FROM B2B_CommerceLog__c
                WHERE B2B_Related_Record_Id__c = :lensConfiguratorList[0].B2B_Account__c
            ];
        }
        Test.stopTest();
        Assert.areEqual(false, commerceLogsList.isEmpty(), 'Commerce Logs should get created as Callout is failed due to OMA Data error');
    }

    //BS-1248
    @isTest
    private static void performSchneiderCalloutProcessingForServerErrorTest() {
        List<Product2> productList = B2B_TestDataFactory.createProductsForLensConfigurator();
        insert productList;

        List<B2B_Lens_Configurator__c> lensConfiguratorList = B2B_TestDataFactory.createCorrectRecordsForLensConfigurator();
        insert lensConfiguratorList;

        List<B2B_Lens_Shapes__c> lensShapeList = B2B_TestDataFactory.createCorrectRecordsForLensShapes();
        insert lensShapeList;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new B2B_TestDataFactory.B2B_SchneiderCalloutMockInterface(503, false));
        B2B_VisionSensationUtility vsUtility = new B2B_VisionSensationUtility();
        B2B_VisionSensationUtility.B2B_SchneiderRequest request = new B2B_VisionSensationUtility.B2B_SchneiderRequest();
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper responseWrapper = vsUtility.performSchneiderCallout(request);
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper parsedResponseWrapper = B2B_Utils.performSchneiderCalloutProcessing(
            responseWrapper,
            String.valueOf(lensConfiguratorList[0].Id)
        );
        List<B2B_Lens_Configurator__c> parsedLensConfiguratorList = [
            SELECT Id, B2B_Account__c, B2B_Account__r.k_ARIS_Account_ID__c, B2B_Account__r.k_Account_No__c, B2B_ARIS_Account_Id__c
            FROM B2B_Lens_Configurator__c
            WHERE Id = :lensConfiguratorList[0].Id
        ];
        List<B2B_CommerceLog__c> commerceLogsList = new List<B2B_CommerceLog__c>();
        if (parsedLensConfiguratorList.isEmpty() == false) {
            commerceLogsList = [
                SELECT Id, B2B_Message__c, B2B_Process__c, B2B_Type__c, B2B_Related_Record_Id__c
                FROM B2B_CommerceLog__c
                WHERE B2B_Related_Record_Id__c = :lensConfiguratorList[0].B2B_Account__c
            ];
        }
        Test.stopTest();
        Assert.areEqual(false, commerceLogsList.isEmpty(), 'Commerce Logs should get created as Callout is failed due to Server Error');
    }

    //BS-1248
    @isTest
    private static void performSchneiderCalloutProcessingForSchneiderServerErrorTest() {
        List<Product2> productList = B2B_TestDataFactory.createProductsForLensConfigurator();
        insert productList;

        List<B2B_Lens_Configurator__c> lensConfiguratorList = B2B_TestDataFactory.createCorrectRecordsForLensConfigurator();
        insert lensConfiguratorList;

        List<B2B_Lens_Shapes__c> lensShapeList = B2B_TestDataFactory.createCorrectRecordsForLensShapes();
        insert lensShapeList;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new B2B_TestDataFactory.B2B_SchneiderCalloutMockInterface(200, null));
        B2B_VisionSensationUtility vsUtility = new B2B_VisionSensationUtility();
        B2B_VisionSensationUtility.B2B_SchneiderRequest request = new B2B_VisionSensationUtility.B2B_SchneiderRequest();
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper responseWrapper = vsUtility.performSchneiderCallout(request);
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper parsedResponseWrapper = B2B_Utils.performSchneiderCalloutProcessing(
            responseWrapper,
            String.valueOf(lensConfiguratorList[0].Id)
        );
        List<B2B_Lens_Configurator__c> parsedLensConfiguratorList = [
            SELECT Id, B2B_Account__c, B2B_Account__r.k_ARIS_Account_ID__c, B2B_Account__r.k_Account_No__c, B2B_ARIS_Account_Id__c
            FROM B2B_Lens_Configurator__c
            WHERE Id = :lensConfiguratorList[0].Id
        ];
        List<B2B_CommerceLog__c> commerceLogsList = new List<B2B_CommerceLog__c>();
        if (parsedLensConfiguratorList.isEmpty() == false) {
            commerceLogsList = [
                SELECT Id, B2B_Message__c, B2B_Process__c, B2B_Type__c, B2B_Related_Record_Id__c
                FROM B2B_CommerceLog__c
                WHERE B2B_Related_Record_Id__c = :lensConfiguratorList[0].B2B_Account__c
            ];
        }
        Test.stopTest();
        Assert.areEqual(false, commerceLogsList.isEmpty(), 'Commerce Logs should get created as Callout is failed due to Schneider Server Error');
    }

    //BS-1248
    // Test method for the scenario of any unknown error during schneider callout
    @isTest
    private static void performSchneiderCalloutProcessingForSchneiderErrorTest() {
        List<Product2> productList = B2B_TestDataFactory.createProductsForLensConfigurator();
        insert productList;

        List<B2B_Lens_Configurator__c> lensConfiguratorList = B2B_TestDataFactory.createCorrectRecordsForLensConfigurator();
        insert lensConfiguratorList;

        List<B2B_Lens_Shapes__c> lensShapeList = B2B_TestDataFactory.createCorrectRecordsForLensShapes();
        insert lensShapeList;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new B2B_TestDataFactory.B2B_SchneiderCalloutMockInterface(0, null));
        B2B_VisionSensationUtility vsUtility = new B2B_VisionSensationUtility();
        B2B_VisionSensationUtility.B2B_SchneiderRequest request = new B2B_VisionSensationUtility.B2B_SchneiderRequest();
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper responseWrapper = vsUtility.performSchneiderCallout(request);
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper parsedResponseWrapper = B2B_Utils.performSchneiderCalloutProcessing(
            responseWrapper,
            String.valueOf(lensConfiguratorList[0].Id)
        );
        List<B2B_Lens_Configurator__c> parsedLensConfiguratorList = [
            SELECT Id, B2B_Account__c, B2B_Account__r.k_ARIS_Account_ID__c, B2B_Account__r.k_Account_No__c, B2B_ARIS_Account_Id__c
            FROM B2B_Lens_Configurator__c
            WHERE Id = :lensConfiguratorList[0].Id
        ];
        List<B2B_CommerceLog__c> commerceLogsList = new List<B2B_CommerceLog__c>();
        if (parsedLensConfiguratorList.isEmpty() == false) {
            commerceLogsList = [
                SELECT Id, B2B_Message__c, B2B_Message_Details__c, B2B_Process__c, B2B_Type__c, B2B_Related_Record_Id__c
                FROM B2B_CommerceLog__c
                WHERE B2B_Related_Record_Id__c = :lensConfiguratorList[0].B2B_Account__c
            ];
        }
        Test.stopTest();
        Assert.areEqual(false, commerceLogsList.isEmpty(), 'Commerce Logs should get created as Callout is failed due to Schneider Server Error');
    }

    //BS-1248
    @isTest
    private static void performSchneiderCalloutProcessingForEmptyInputsTest() {
        Test.startTest();
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper parsedResponseWrapper = B2B_Utils.performSchneiderCalloutProcessing(null, null);
        Test.stopTest();
        Assert.areEqual(false, parsedResponseWrapper != null, 'Nothing should be returned as inputs are invalid');
    }

    //BS-1278
    @IsTest
    public static void getCountrySpecificDetailsTest() {
        B2B_TestDataFactory.createCountrySpecificPreferenceSettingRecords();
        Account accountObj = B2B_TestDataFactory.createTestAccount();
        accountObj.Store_Country__c = 'Germany';
        accountObj.Brand__c = 'Silhouette';
        insert accountObj;
        Contact contactObj = B2B_TestDataFactory.createInsertDefaultContact(accountObj);
        User commerceUserObj = new User();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            commerceUserObj = B2B_TestDataFactory.createInsertCommerceUser(contactObj.Id);
        }

        Test.startTest();
        B2B_Utils.B2B_FooterContentWrapper footerContentObj = B2B_Utils.getCountrySpecificDetails(commerceUserObj.Id);
        Test.stopTest();

        System.assertNotEquals(null, footerContentObj, 'Wrapper object should be returned');
    }
    //Added below methods to increase the code coverage for B2B_Utils class as a part of BS-1663 ticket.
    @IsTest
    public static void checkAccountClosedForNBTest() {
        Account accountObj = B2B_TestDataFactory.createTestAccount();
        accountObj.k_Account_Closed_NB__c = '1';
        insert accountObj;
        Test.startTest();
        Boolean AccountStatusResult = B2B_Utils.checkAccountClosedForNB(accountObj.Id);
        Test.stopTest();
        System.assertEquals(true, AccountStatusResult, 'Account status is closed.');
    }

    //BS-1714
    @IsTest
    public static void checkAccountClosedForSHTest() {
        Account accountObj = B2B_TestDataFactory.createTestAccount();
        accountObj.k_Account_Closed_SH__c = '1';
        accountObj.k_Account_Status_Silhouette__c = '1';
        insert accountObj;
        Test.startTest();
        Boolean AccountStatusResult = B2B_Utils.checkAccountClosedForSH(accountObj.Id);
        Test.stopTest();
        System.assertEquals(true, AccountStatusResult, 'Account status is closed for Silhouette.');
    }

    //BS-1714
    @IsTest
    public static void checkAccountClosedForEETest() {
        Account accountObj = B2B_TestDataFactory.createTestAccount();
        accountObj.k_Account_Closed_EE__c = '1';
        accountObj.Acct_Stat_EE__c = '1';
        insert accountObj;
        Test.startTest();
        Boolean AccountStatusResult = B2B_Utils.checkAccountClosedForEE(accountObj.Id);
        Test.stopTest();
        System.assertEquals(true, AccountStatusResult, 'Account status is closee for evil eye.');
    }

    //BS-1953
    @IsTest
    public static void checkHideAccountClosurePopupTest() {
        Account accountObj = [SELECT Id FROM Account LIMIT 1];
        Test.startTest();
        My_B2B_Shop_Preference__c shopPreference = B2B_Utils.checkHideAccountClosurePopup(accountObj.Id);
        Test.stopTest();
        System.assertNotEquals(null, shopPreference, 'It should return one record');
    }

    //BS-1953
    @isTest
    public static void updateMyB2BShopPreferenceTest() {
        Account accountObj = [SELECT Id FROM Account LIMIT 1];

        Test.startTest();
        B2B_Utils.updateMyB2BShopPreference(accountObj.Id);
        Test.stopTest();
        List<My_B2B_Shop_Preference__c> shopPreferenceList = [
            SELECT Id, B2B_Hide_Account_Closure_Popup__c
            FROM My_B2B_Shop_Preference__c
            WHERE B2B_Account__c = :accountObj.Id
        ];
        System.assertEquals(true, shopPreferenceList[0].B2B_Hide_Account_Closure_Popup__c, 'field should have true value');
    }
    //BS-1849
    @IsTest
    private static void setPasswordForValidInputsTest() {
        List<User> userList = [SELECT Id, Name FROM User LIMIT 1];
        String password = 'Test@1234';
        Test.startTest();
        Id jobId = B2B_Utils.setPassword(userList[0].Id, password);
        Test.stopTest();
        Assert.areEqual(false, jobId == null, 'Apex Job Id should not be empty as we have supplied correct inputs while invoking the method');
    }

    //BS-1849
    @IsTest
    private static void setPasswordForInValidInputsTest() {
        List<User> userList = [SELECT Id, Name FROM User LIMIT 1];
        String password = 'Test@1234';
        Test.startTest();
        Id jobId = B2B_Utils.setPassword(null, password);
        Test.stopTest();
        Assert.areEqual(true, jobId == null, 'Apex Job Id should be empty as we have supplied incorrect inputs while invoking the method');
    }

    //BS-1849
    @IsTest
    private static void fetchUserAssociatedWithAccountTest() {
        List<Account> accountList = [SELECT Id, Name FROM Account LIMIT 1];
        Test.startTest();
        List<User> userList = new List<User>();
        userList = B2B_Utils.fetchUserAssociatedWithAccount(String.valueOf(accountList[0].Id));
        Test.stopTest();
        Assert.areEqual(true, userList == null, 'User records should not be returned as no user is associated with provided account');
    }

    //BS-1849
    @IsTest
    private static void getProcessStatusTest() {
        List<User> userList = [SELECT Id, Name FROM User LIMIT 1];
        String password = 'Test@1234';
        Test.startTest();
        Id jobId = B2B_Utils.setPassword(userList[0].Id, password);
        List<AsyncApexJob> apexJobList = B2B_Utils.getProcessStatus(jobId, userList[0].Id);
        Test.stopTest();
        Assert.areEqual(false, apexJobList.isEmpty(), 'Apex Job List should not be empty as we have supplied correct inputs while invoking the method');
    }

    //BS-1248
    @isTest
    private static void performSchneiderCalloutProcessingPreCalcGuidMissingTest() {
        List<Product2> productList = B2B_TestDataFactory.createProductsForLensConfigurator();
        insert productList;

        List<B2B_Lens_Configurator__c> lensConfiguratorList = B2B_TestDataFactory.createCorrectRecordsForLensConfigurator();
        insert lensConfiguratorList;

        List<B2B_Lens_Shapes__c> lensShapeList = B2B_TestDataFactory.createCorrectRecordsForLensShapes();
        insert lensShapeList;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new B2B_TestDataFactory.B2B_SchneiderCalloutMockInterface(200, false));
        B2B_VisionSensationUtility vsUtility = new B2B_VisionSensationUtility();
        B2B_VisionSensationUtility.B2B_SchneiderRequest request = new B2B_VisionSensationUtility.B2B_SchneiderRequest();
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper responseWrapper = vsUtility.performSchneiderCallout(request);
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper parsedResponseWrapper = B2B_Utils.performSchneiderCalloutProcessing(
            responseWrapper,
            String.valueOf(lensConfiguratorList[0].Id)
        );
        List<B2B_Lens_Configurator__c> parsedLensConfiguratorList = [
            SELECT Id, B2B_Account__c, B2B_Account__r.k_ARIS_Account_ID__c, B2B_Account__r.k_Account_No__c, B2B_ARIS_Account_Id__c
            FROM B2B_Lens_Configurator__c
            WHERE Id = :lensConfiguratorList[0].Id
        ];
        List<B2B_CommerceLog__c> commerceLogsList = new List<B2B_CommerceLog__c>();
        if (parsedLensConfiguratorList.isEmpty() == false) {
            commerceLogsList = [
                SELECT Id, B2B_Message__c, B2B_Process__c, B2B_Type__c, B2B_Related_Record_Id__c
                FROM B2B_CommerceLog__c
                WHERE B2B_Related_Record_Id__c = :lensConfiguratorList[0].B2B_Account__c
            ];
        }
        Test.stopTest();
        Assert.areEqual(false, commerceLogsList.isEmpty(), 'Commerce Logs should get created as Callout is failed due to calculation error');
    }

    //BS-1914
    @isTest
    private static void performSchneiderCalloutProcessingForSuccessfulCalloutButMissingCalcGuidTest() {
        List<Product2> productList = B2B_TestDataFactory.createProductsForLensConfigurator();
        insert productList;

        List<B2B_Lens_Configurator__c> lensConfiguratorList = B2B_TestDataFactory.createCorrectRecordsForLensConfigurator();
        insert lensConfiguratorList;

        List<B2B_Lens_Shapes__c> lensShapeList = B2B_TestDataFactory.createCorrectRecordsForLensShapes();
        insert lensShapeList;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new B2B_TestDataFactory.B2B_SchneiderCalloutMockInterface(100, true));
        B2B_VisionSensationUtility vsUtility = new B2B_VisionSensationUtility();
        B2B_VisionSensationUtility.B2B_SchneiderRequest request = new B2B_VisionSensationUtility.B2B_SchneiderRequest();
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper responseWrapper = vsUtility.performSchneiderCallout(request);
        B2B_VisionSensationUtility.B2B_SchneiderCalloutResponseWrapper parsedResponseWrapper = B2B_Utils.performSchneiderCalloutProcessing(
            responseWrapper,
            String.valueOf(lensConfiguratorList[0].Id)
        );
        List<B2B_Lens_Configurator__c> parsedLensConfiguratorList = [
            SELECT Id, B2B_Account__c, B2B_Account__r.k_ARIS_Account_ID__c, B2B_Account__r.k_Account_No__c, B2B_ARIS_Account_Id__c
            FROM B2B_Lens_Configurator__c
            WHERE Id = :lensConfiguratorList[0].Id
        ];
        List<B2B_CommerceLog__c> commerceLogsList = new List<B2B_CommerceLog__c>();
        if (parsedLensConfiguratorList.isEmpty() == false) {
            commerceLogsList = [
                SELECT Id, B2B_Message__c, B2B_Process__c, B2B_Type__c, B2B_Related_Record_Id__c
                FROM B2B_CommerceLog__c
                WHERE B2B_Related_Record_Id__c = :lensConfiguratorList[0].B2B_Account__c
            ];
        }
        Test.stopTest();
        Assert.areEqual(false, commerceLogsList.isEmpty(), 'Commerce Logs should get created as Callout is failed due to Server Error');
    }
}