force-app/main/default/objects/B2B_Commerce_Product_Link__c/B2B_Commerce_Product_Link__c.object-meta.xml
<CustomObject>
    <label>B2B Commerce Product Link</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>B2B Commerce Product Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Commerce Product Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B2B_Commerce_Product_Link__c/fields/B2B_Type__c.field-meta.xml
<CustomField>
    <fullName>B2B_Type__c</fullName>
    <description>Type to define what kind of relation two entities have. This is further used to filter/display only specific relation types</description>
    <inlineHelpText>Type to define what kind of relation two entities have. This is further used to filter/display only specific relation types</inlineHelpText>
    <label>Relation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessory</fullName>
            </value>
            <value>
                <fullName>Cross Sell</fullName>
            </value>
            <value>
                <fullName>Related</fullName>
            </value>
            <value>
                <fullName>Spare Part</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Style Shades</fullName>
            </value>
            <value>
                <fullName>Demo to Chassis</fullName>
            </value>
            <value>
                <fullName>Lenses</fullName>
            </value>
            <value>
                <fullName>Clip-in</fullName>
            </value>
            <value>
                <fullName>Adapter</fullName>
            </value>
            <value>
                <fullName>Direct Glazing</fullName>
            </value>
            <value>
                <fullName>Special Variation Parent</fullName>
            </value>
            <value>
                <fullName>Lens Color</fullName>
            </value>
            <value>
                <fullName>Photo Sensation</fullName>
            </value>
            <value>
                <fullName>Blue Sensation</fullName>
            </value>
            <value>
                <fullName>Anti Reflection</fullName>
            </value>
            <value>
                <fullName>Hard Coating</fullName>
            </value>
            <value>
                <fullName>glazed to unglazed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/B2B_FeaturedProductTypes.cls
/**
 * @author Matthias Lindner
 * @email mlindner@salesforce.com
 * @create date 2022-06-27 14:44:45
 * @modify date 2022-06-27 14:44:45
 * @desc used for related product component
 */

public class B2B_FeaturedProductTypes extends VisualEditor.DynamicPickList {
    public override VisualEditor.DataRow getDefaultValue() {
        Schema.DescribeFieldResult fieldResult = B2B_Commerce_Product_Link__c.B2B_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        VisualEditor.DataRow defaultValue = new VisualEditor.DataRow(ple[0].getLabel(), ple[0].getValue());
        return defaultValue;
    }

    public override VisualEditor.DynamicPickListRows getValues() {
        VisualEditor.DynamicPickListRows availableRelationTypes = new VisualEditor.DynamicPickListRows();
        Schema.DescribeFieldResult fieldResult = B2B_Commerce_Product_Link__c.B2B_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry pickListVal : ple) {
            availableRelationTypes.addRow(new VisualEditor.DataRow(pickListVal.getLabel(), pickListVal.getValue()));
        }
        return availableRelationTypes;
    }
}