force-app/main/default/objects/B2B_Color_Filters__mdt/B2B_Color_Filters__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata used to define the color filters and HEX codes.</description>
    <label>Color Filter</label>
    <pluralLabel>Color Filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/B2B_Product_Image__c/B2B_Product_Image__c.object-meta.xml
<CustomObject>
    <label>B2B Product Image</label>
    <nameField>
        <displayFormat>ProductImage-{000000}</displayFormat>
        <label>B2B Product Image Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Product Image</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B2B_Product_Image__c/fields/B2B_External_Id__c.field-meta.xml
<CustomField>
    <fullName>B2B_External_Id__c</fullName>
    <description>Holds the external Id from the ERP.</description>
    <externalId>true</externalId>
    <label>B2B External Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/B2B_Product_Image__c/fields/B2B_Image_Alt_Text__c.field-meta.xml
<CustomField>
    <fullName>B2B_Image_Alt_Text__c</fullName>
    <label>Image Alt Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B2B_Product_Image__c/fields/B2B_Image_Order__c.field-meta.xml
<CustomField>
    <fullName>B2B_Image_Order__c</fullName>
    <label>Image Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/B2B_Product_Image__c/fields/B2B_Image_Title__c.field-meta.xml
<CustomField>
    <fullName>B2B_Image_Title__c</fullName>
    <label>Image Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B2B_Product_Image__c/fields/B2B_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>B2B_Image_URL__c</fullName>
    <label>Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/B2B_Product_Image__c/fields/B2B_Product__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Product Image</relationshipLabel>
    <relationshipName>B2B_Product_Image</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/B2B_Product_Image__c/fields/D2C_Product_Image_Type__c.field-meta.xml
<CustomField>
    <fullName>D2C_Product_Image_Type__c</fullName>
    <description>The field will help to identify the type of image stored</description>
    <label>D2C Product Image Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Model Image</fullName>
            </value>
            <value>
                <fullName>Product Image</fullName>
            </value>
            <value>
                <fullName>Packaging Image</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/D2C_ProductCardController.cls
/*************************************************************************************************************
 * Controller class for NBD2C Store PLP page
 *  @author – Shrihari Kendre
 *  @email shrihari.kendre@theblueflamelabs.com
 *  @create date 2024-04-15 16:18:32
 ***************************************************************************************************************/
public without sharing class D2C_ProductCardController {
    /**
     * @description Get product Images from B2B_Product_Image__c Object based on product Ids
     * @author Shrihari Kendre
     * @param  productIds  List of product Ids
     * @return   List<B2B_Product_Image__c>
     */
    @AuraEnabled(cacheable=true)
    public static List<B2B_Product_Image__c> getProductImages(List<String> productIds) {
        List<B2B_Product_Image__c> productImageList = [
            SELECT Name, B2B_Image_Alt_Text__c, B2B_Image_Order__c, B2B_Image_Title__c, B2B_Image_URL__c, B2B_Product__c, B2B_External_Id__c
            FROM B2B_Product_Image__c
            WHERE B2B_Product__c IN :productIds AND D2C_Product_Image_Type__c = :D2C_Constants.MODEL_IMAGE
        ];
        return productImageList;
    }

    /**
     * @description Get metadata for the color values and hex codes
     * @author Shrihari Kendre
     * @return   Map of Color Metadata
     */
    @AuraEnabled(cacheable=true)
    public static String getColorsMetadata() {
        Map<String, B2B_Color_Filters__mdt> mapColorCodes = B2B_Color_Filters__mdt.getAll();
        return JSON.serialize(mapColorCodes);
    }
}